### ISSUE TITLE
Can't get custom field?

### ISSUE THREAD

**Issue by thearabbit** [peerlibrary/meteor-user-extra#3]
I create custom field like this
```js
{
	"_id" : "ZwGic4efjwsRAWhCa",
	"createdAt" : ISODate("2017-06-07T08:25:14.076+07:00"),
	"services" : {
		"password" : {
			"bcrypt" : "$2a$10$0YNyHPPLBoDZdbZs.Qocuef9tTjpIV.5vSSJyM61XGpsc9CmJmBm2"
		}
	},
	"username" : "super",
	"emails" : [
		{
			"address" : "super@rabbit.com",
			"verified" : false
		}
	],
	"email" : "super@rabbit.com",
	"password" : "rabbitsuper",
	"profile" : {
		"fullName" : "Theara",
		"branchPermissions" : [
			"001"
		],
		"roleGroup" : "Super"
	},
	"branchPermissions" : [
		"001"
	],
	"roleGroup" : "Super",
	"roles" : [
		"super"
	]
}
```
But I can't get `Meteor.user({username: 1, profile: 1, branchPermissions: 1, roleGroup: 1})`.
Please help me.

**Comment by mitar** [comment]
Are you trying this on client or server? On client you have to publish those extra information.

**Comment by thearabbit** [comment]
Thanks for your reply.
I use this on client.

**Comment by mitar** [comment]
You have to publish all data you want to use on the client from the server. It seems you are not publishing data for your user collection.

**Comment by mitar** [comment]
BTW, also I suggest you do not paste your hashed passwords into issues on GitHub.
