### ISSUE TITLE
ReferenceError: ClassyTestCase is not defined

### ISSUE THREAD

**Issue by flameuzumo** [peerlibrary/meteor-user-extra#4]
Hi there,
I get error ReferenceError: ClassyTestCase is not defined when running against meteor 1.8.0.1. I do not get an error when running against meteor 1.4.4.1. Please help.

**Comment by flameuzumo** [comment]
I did not have package/package.js in my project. I have since added package.js as in your code here in this package, but it did not work. Please help.

**Comment by mitar** [comment]
I republished the package with the latest Meteor and I think this fixed the issue. Try `peerlibrary:user-extra@0.5.0`.
